- hosts: all
  become: yes
  tasks:
    - apt:
        pkg:
          - ansible
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - curl
          - git
    - git:
        repo: https://github.com/waffleboot/MTProxy
        depth: 1
        dest: MTProxy
    - shell: cd MTProxy && make
    - debug:
        msg: "tg://proxy?server={{ansible_host}}&port=443&secret={{token}}"
    - copy:
        dest: start.sh
        mode: "u+x"
        content: |
          #!/bin/bash
          curl -s https://core.telegram.org/getProxySecret -o proxy-secret
          curl -s https://core.telegram.org/getProxyConfig -o proxy-multi.conf
          /home/ubuntu/MTProxy/objs/bin/mtproto-proxy -u nobody -H 443 -S {{token}} --aes-pwd proxy-secret proxy-multi.conf -M 5 --nat-info {{ hostvars['master']['ansible_default_ipv4']['address'] }}:{{ansible_host}}
    - copy:
        dest: /etc/systemd/system/mtproxy.service
        content: |
          [Unit]
          Description=MTProxy
          After=multi-user.target
          
          [Service]
          Type=simple
          ExecStart=/bin/bash /home/ubuntu/start.sh
          Restart=always
          RestartSec=30
          
          [Install]
          WantedBy=multi-user.target
    - systemd:
        name: mtproxy
        daemon_reload: yes
        state: restarted
        enabled: yes
    - cron:
        job: "systemctl restart mtproxy"
        minute: "0"
