- hosts: all
  become: yes
  tasks:
    - apt:
        pkg:
          - ansible
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - curl
          - git
    - git:
        repo: https://github.com/waffleboot/MTProxy
        depth: 1
        dest: MTProxy
    - command:
        chdir: MTProxy
        cmd: make
    - copy:
        dest: /etc/systemd/system/mtproxy.service
        content: |
          [Unit]
          Description=MTProxy
          After=multi-user.target
          
          [Service]
          ExecStartPre=/usr/bin/curl -s https://core.telegram.org/getProxySecret -o /tmp/proxy-secret
          ExecStartPre=/usr/bin/curl -s https://core.telegram.org/getProxyConfig -o /tmp/proxy-multi.conf
          ExecStart=/home/ubuntu/MTProxy/objs/bin/mtproto-proxy -u nobody -H 443 -S {{token}} --aes-pwd /tmp/proxy-secret /tmp/proxy-multi.conf -M 5 --nat-info {{ hostvars['master']['ansible_default_ipv4']['address'] }}:{{ansible_host}}
          Restart=always
          RestartSec=30
          
          [Install]
          WantedBy=multi-user.target
    - systemd:
        name: mtproxy
        daemon_reload: yes
        state: restarted
        enabled: yes
    - cron:
        job: "systemctl restart mtproxy"
        minute: "0"
