- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: wait connection
      shell: |
        until ssh -i {{ansible_ssh_private_key_file}} -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ansible_user}}@{{ansible_host}} -p {{ansible_port|default(22)}} echo ok 2>&1;
        do
          :;
        done
      delegate_to: localhost
    - name: apt update
      raw: |
        until apt update;
        do
          echo sleep;
          sleep 1;
        done
    - block:
        - name: apt install python
          no_log: True
          raw: |
            for i in {1..5}
            do
              apt install -y python 2>apt_install_python.log;
              status=$?
              if [ $status -eq 0 ]
              then
                break
              fi
              sleep 3
            done
            exit $status
      rescue:
        - command: cat apt_install_python.log
          register: log
        - debug: msg="{{log.stdout_lines}}"
