- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - shell: |
        until ssh -i {{ansible_ssh_private_key_file}} -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ansible_user}}@{{ansible_host}} -p {{ansible_port|default(22)}} echo ok 2>&1;
        do
          :;
        done
      delegate_to: localhost
    - raw: apt update && apt install -y python
